"use client";
import { useState } from "react";
import { register } from "@/services/auth_service";
import { useRouter } from "next/navigation";
import APP_ROUTES from "@/const/app_routes";
import APP_MESSAGES from "@/const/app_messages";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AlertError } from "@/app/components/AlertError";
import Link from "next/link";
import AppLogo from "@/app/components/AppLogo";

// export const metadata = {
// 	title: "Next.js",
// 	description: "Generated by Next.js",
// };

const Login = () => {
	const [firstName, setFirstName] = useState<string>("");
	const [lastName, setLastName] = useState<string>("");
	const [age, setAge] = useState<number>(1);
	const [email, setEmail] = useState<string>("");
	const [password, setPassword] = useState<string>("");
	const [passwordConfirmation, setPasswordConfirmation] = useState<string>("");
	const [error, setError] = useState<string>("");
	const router = useRouter();

	const handleLogin = async (e: React.FormEvent) => {
		e.preventDefault();
		try {
			await register({ first_name: firstName, last_name: lastName, age: age, email, password, password_confirmation: passwordConfirmation });
			router.push(APP_ROUTES.posts.index);
		} catch (err) {
			setError(APP_MESSAGES.auth.failed);
		}
	};

	return (
		<form onSubmit={handleLogin} className="h-full w-full flex justify-center items-center">
			<div className="">
				<AppLogo className="mx-auto w-24 h-24 text-primary mb-3" />
				<h2 className="font-bold text-3xl text-center mb-3 text-primary">{APP_MESSAGES.app_name}</h2>
				<Card className="w-full max-w-sm">
					<CardHeader className="text-center">
						<CardTitle className="text-2xl">{APP_MESSAGES.register}</CardTitle>
						<CardDescription>{APP_MESSAGES.register_cta}</CardDescription>
					</CardHeader>
					<CardContent className="grid gap-4">
						<div className="grid grid-cols-2 gap-4">
							<div className="grid gap-2">
								<Label htmlFor="first-name">{APP_MESSAGES.first_name}</Label>
								<Input id="first-name" placeholder="Hosanna" required value={firstName} onChange={(e) => setFirstName(e.target.value)} />
							</div>
							<div className="grid gap-2">
								<Label htmlFor="last-name">{APP_MESSAGES.last_name}</Label>
								<Input id="last-name" placeholder="Amané" required value={lastName} onChange={(e) => setLastName(e.target.value)} />
							</div>
						</div>
						<div className="grid gap-2">
							<Label htmlFor="age">Age</Label>
							<Input id="age" type="number" placeholder="25" min={1} value={age} onChange={(e) => setAge(parseInt(e.target.value))} required />
						</div>
						<div className="grid gap-2">
							<Label htmlFor="email">{APP_MESSAGES.email}</Label>
							<Input id="email" type="email" placeholder="amane.dev@gmail.com" value={email} onChange={(e) => setEmail(e.target.value)} required />
						</div>
						<div className="grid gap-2">
							<Label htmlFor="password">{APP_MESSAGES.password}</Label>
							<Input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required />
						</div>
						<div className="grid gap-2">
							<Label htmlFor="password">{APP_MESSAGES.password_confirmation}</Label>
							<Input id="password_confirmation" type="password" value={passwordConfirmation} onChange={(e) => setPasswordConfirmation(e.target.value)} required />
						</div>
					</CardContent>

					{error && (
						<div className="p-5 pt-0">
							<AlertError message={error} />
						</div>
					)}
					<CardFooter>
						<Button className="w-full">{APP_MESSAGES.submit_register}</Button>
					</CardFooter>

					<div className="px-5 flex justify-between items-center py-3">
						<CardDescription>{APP_MESSAGES.has_account}</CardDescription>
						<Button variant="link">
							<Link href={APP_ROUTES.login}>{APP_MESSAGES.submit_login}</Link>
						</Button>
					</div>
				</Card>
			</div>
		</form>
	);
};

export default Login;
